/** The migration report (migrate spec §4.2): every gate as a tally,
 * the review lists, and the evidence doc the maintainer blesses. */
import type { QuarantineRow, Unresolved } from './cite.ts';
import { tally } from './gates.ts';
import type { Tally, TruthEntry } from './types.ts';

const REPORT_PATH = 'data/source/migration-report.json';
const BLESSING_PATH = 'docs/v2/migration-blessing.md';

const GATE_NAMES = [
	'bodyRoundTrips',
	'headwordRoundTrip',
	'textConservation',
	'schema',
	'chain',
	'internalTargets',
	'slugs',
	'pages',
	'composition',
] as const;
type GateName = (typeof GATE_NAMES)[number];

interface Report {
	entries: number;
	gates: Record<GateName, Tally>;
	headwordReview: string[];
	/** `rid: path: …` lines from `finishEntry` noting an inline tag run
	 * that crossed a body-unit boundary or was closed at the end of its
	 * sense sequence (migrate spec §2.2/§4.2, fix round 1). Informational
	 * — never a gate failure. */
	markupCarries: string[];
	nonHighPages: string[];
	/** Informational patch accounting (Ruling F): the accepted corpus
	 * size, how many patches applied, and the carry-over split between
	 * those a transform rule already absorbed and those still carried.
	 * Not a gate — patch PROBLEMS are gate 9. */
	patches: {
		absorbed: number;
		accepted: number;
		applied: number;
		carried: number;
	};
	quarantine: QuarantineRow[];
	/** collision size → number of stems of that size */
	slugCollisions: Record<string, number>;
	unresolved: Unresolved[];
	written: number;
}

interface Sample {
	rid: string;
	source: unknown;
	truth: TruthEntry;
}

function createReport(): Report {
	const gates = Object.fromEntries(
		GATE_NAMES.map((name) => [name, tally()]),
	) as Record<GateName, Tally>;
	return {
		entries: 0,
		gates,
		headwordReview: [],
		markupCarries: [],
		nonHighPages: [],
		patches: { absorbed: 0, accepted: 0, applied: 0, carried: 0 },
		quarantine: [],
		slugCollisions: {},
		unresolved: [],
		written: 0,
	};
}

function isGreen(report: Report): boolean {
	if (report.entries === 0) {
		return false;
	}
	return GATE_NAMES.every((name) => {
		const t = report.gates[name];
		const reached = name === 'internalTargets' || t.total > 0;
		return reached && t.pass === t.total && t.failures.length === 0;
	});
}

async function writeReport(report: Report, path = REPORT_PATH): Promise<void> {
	await Bun.write(path, `${JSON.stringify(report, null, '\t')}\n`);
}

function fence(value: unknown): string {
	return `\`\`\`json\n${JSON.stringify(value, null, '\t')}\n\`\`\``;
}

function list(lines: readonly string[], empty: string): string {
	return lines.length === 0
		? `_${empty}_`
		: lines.map((l) => `- ${l}`).join('\n');
}

function gateRows(report: Report): string[] {
	return GATE_NAMES.map(
		(name) =>
			`| ${name} | ${report.gates[name].pass} / ${report.gates[name].total} | ${report.gates[name].failures.length} |`,
	);
}

function collisionRows(report: Report): string[] {
	return Object.entries(report.slugCollisions)
		.sort(([a], [b]) => Number(a) - Number(b))
		.map(([size, count]) => `| ${size} | ${count} |`);
}

function sampleSections(samples: readonly Sample[]): string[] {
	return samples.flatMap((s) => [
		`### ${s.rid}`,
		'',
		'Source (composed):',
		'',
		fence(s.source),
		'',
		'Truth:',
		'',
		fence(s.truth),
		'',
	]);
}

function renderBlessing(report: Report, samples: readonly Sample[]): string {
	return [
		'# Migration blessing — evidence',
		'',
		`Generated by \`bun pipeline:migrate\` over ${report.entries} entries. ${isGreen(report) ? 'Every gate is green.' : 'At least one gate is RED.'}`,
		'',
		`Patch corpus: ${report.patches.accepted} accepted, ${report.patches.applied} applied, ${report.patches.absorbed} carry-over absorbed, ${report.patches.carried} carried.`,
		'',
		'## Gates',
		'',
		'| Gate | pass / total | failures |',
		'|---|---|---|',
		...gateRows(report),
		'',
		'## Headword review',
		'',
		list(report.headwordReview, 'none'),
		'',
		'## Markup carried across unit boundaries',
		'',
		list(report.markupCarries, 'none'),
		'',
		'## Page placements needing review',
		'',
		list(report.nonHighPages, 'none'),
		'',
		'## Slug collisions',
		'',
		'| members per stem | stems |',
		'|---|---|',
		...collisionRows(report),
		'',
		'## Quarantined internal targets',
		'',
		list(
			report.quarantine.map((q) => `${q.rid} → \`${q.target}\` — ${q.note}`),
			'none',
		),
		'',
		'## Samples',
		'',
		...sampleSections(samples),
	].join('\n');
}

export type { GateName, Report, Sample };
export {
	BLESSING_PATH,
	createReport,
	GATE_NAMES,
	isGreen,
	REPORT_PATH,
	renderBlessing,
	writeReport,
};
