/** The review report (consolidation spec §3.1.1): every review and
 * patch row of a run, split by whether it blocks v2 publication. The
 * admin tool's tracker integration reads the deferred rows. */
import type { Publication, Report, ReportRow } from './report.ts';

const REVIEW_REPORT_PATH = 'docs/v2/review-report.md';

const SECTIONS: ReadonlyArray<readonly [Publication, string]> = [
	['blocks', 'Before publication'],
	['defer', 'Deferred'],
	['note', 'Notes'],
];

/** One section: a `###` block per kind, kinds alphabetical, rows in
 * run order; `_none_` when the section is empty. */
function section(title: string, rows: readonly ReportRow[]): string[] {
	const head = [`## ${title} (${rows.length})`, ''];
	if (rows.length === 0) {
		return [...head, '_none_'];
	}
	// A fixed locale keeps the committed report's order the same on
	// every machine.
	const kinds = [...new Set(rows.map((r) => r.kind))].toSorted((a, b) =>
		a.localeCompare(b, 'en'),
	);
	return [
		...head,
		...kinds.flatMap((kind, i) => {
			const lines = rows
				.filter((r) => r.kind === kind)
				.map((r) => `- ${r.rid}: ${r.detail}`);
			const block = [`### ${kind} (${lines.length})`, '', ...lines];
			return i === kinds.length - 1 ? block : [...block, ''];
		}),
	];
}

function renderReviewReport(report: Report): string {
	const by = (p: Publication): ReportRow[] =>
		report.rows.filter((r) => r.publication === p);
	return [
		'# Review report',
		'',
		`Generated by \`bun data:import\` over ${report.entries} entries: every review and patch row of the run, by whether it must be resolved before v2 is published (consolidation spec §3.1.1). Deferred rows become tracker issues; notes do not.`,
		'',
		'| Publication | Rows |',
		'|---|---|',
		...SECTIONS.map(([p]) => `| ${p} | ${by(p).length} |`),
		...SECTIONS.flatMap(([p, title]) => ['', ...section(title, by(p))]),
	].join('\n');
}

export { REVIEW_REPORT_PATH, renderReviewReport };
