import { describe, expect, it } from 'bun:test';
import { classifyRows } from './publication.ts';
import type { Report } from './report.ts';
import { createReport, lineRow } from './report.ts';
import { renderReviewReport } from './review-report.ts';

function sample(): Report {
	const report = createReport();
	report.entries = 3;
	report.rows = [
		lineRow('A00003: p1a (medium)', 'page-confidence-medium'),
		lineRow('A00001: ?אִיבּוּס — grammar did not parse', 'headword-unparsed'),
		lineRow('A00002: senses[0].gloss: carried i', 'markup-carry'),
		lineRow('A00004: boom', 'finish-failed', 'pipeline', 'fault'),
	];
	classifyRows(report);
	return report;
}

/** A patch row (object literal, since `lineRow` only builds `review`
 * rows), a note row, and two same-kind rows in a known order. */
function sampleForOrdering(): Report {
	const report = createReport();
	report.entries = 4;
	report.rows = [
		{
			bucket: 'patch',
			detail: 'source now differs from both the before and after',
			kind: 'upstream-changed',
			rid: 'A00010',
			severity: 'review',
		},
		lineRow('A00011: bare stem now free', 'slug-new'),
		lineRow('A00012: p1a (medium)', 'page-confidence-medium'),
		lineRow('A00013: p2b (medium)', 'page-confidence-medium'),
	];
	classifyRows(report);
	return report;
}

describe('renderReviewReport', () => {
	it('renders the exact document', () => {
		expect(renderReviewReport(sample())).toBe(
			[
				'# Review report',
				'',
				'Generated by `bun data:import` over 3 entries: every review and patch row of the run, by whether it must be resolved before v2 is published (consolidation spec §3.1.1). Deferred rows become tracker issues; notes do not.',
				'',
				'| Publication | Rows |',
				'|---|---|',
				'| blocks | 1 |',
				'| defer | 2 |',
				'| note | 0 |',
				'',
				'## Before publication (1)',
				'',
				'### headword-unparsed (1)',
				'',
				'- A00001: ?אִיבּוּס — grammar did not parse',
				'',
				'## Deferred (2)',
				'',
				'### markup-carry (1)',
				'',
				'- A00002: senses[0].gloss: carried i',
				'',
				'### page-confidence-medium (1)',
				'',
				'- A00003: p1a (medium)',
				'',
				'## Notes (0)',
				'',
				'_none_',
			].join('\n'),
		);
	});
	it('never renders a fault', () => {
		expect(renderReviewReport(sample())).not.toContain('A00004');
	});
	it('sections a patch row, a note row, and keeps same-kind run order', () => {
		const rendered = renderReviewReport(sampleForOrdering());
		const beforePublication = rendered.slice(
			rendered.indexOf('## Before publication'),
			rendered.indexOf('## Deferred'),
		);
		expect(beforePublication).toContain('A00010');
		const notes = rendered.slice(rendered.indexOf('## Notes'));
		expect(notes).not.toContain('_none_');
		expect(rendered.indexOf('A00012')).toBeLessThan(rendered.indexOf('A00013'));
	});
});
